version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./ADHD_Web.Server/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl_certs:/etc/ssl/certs
      - ./ssl_private:/etc/ssl/private
    depends_on:
      - app
