version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./ADHD_Web.Server/Dockerfile
    volumes:
      - .:/app
    networks:
      - adhd_network
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=ADHD_DB;User=root;Password=qwer;
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/certificate.crt:/etc/ssl/certs/certificate.crt:ro
      - ./ssl/private.key:/etc/ssl/private/private.key:ro
    networks:
      - adhd_network
    depends_on:
      - app
  
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwer
      MYSQL_DATABASE: ADHD_DB
    ports:
      - "3306:3306"
    networks:
      - adhd_network
    volumes:
      - adhd_db:/var/lib/mysql

volumes:
  adhd_db:

networks:
  adhd_network:
    driver: bridge