services:
  app:
    build:
      context: .
      dockerfile: ADHD_Web.Server/Dockerfile
    networks:
      - adhd_network
    ports:
      - "8080:8080"
    healthcheck:
      test: []
      interval: 3s
      timeout: 3s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - adhd_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/certificate.crt:/etc/ssl/certs/certificate.crt:ro
      - ./ssl/private.key:/etc/ssl/private/private.key:ro
    depends_on:
      app:
        condition: service_healthy
  
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwer
      MYSQL_DATABASE: ADHD_DB
    ports:
      - "3306:3306"
    networks:
      - adhd_network
    volumes:
      - adhd_db:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mariadb -u root -pqwer -e \"SHOW DATABASES;\"" ]
      interval: 3s
      timeout: 3s
      retries: 3

volumes:
  adhd_db:

networks:
  adhd_network:
    driver: bridge
